title: Jayshree Singh
logo: /assets/img/FB_IMG_1611032649424_2.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working as a Senior MLOPS engineer in SAP.
  Currently Perusing for PG course in AI/ML.
  <br>
  </p>



theme: jekyll-theme-minimal
